### ISSUE TITLE
C-a trace instead of cartoon

### ISSUE THREAD

**Issue by davidjakubec** [dsehnal/LiteMol#22]
Hello,

I noticed some chains in some structures are drawn using C-a trace even when cartoon visualization is selected. See, for example, 1ci6_A. Is this a bug or is trace a fallback option when cartoon cannot be drawn ?

Cheers,
David

**Comment by dsehnal** [comment]
Hi,

unfortunately, this is a problem with the CIF file. If you look at _struct_conf in http://www.ebi.ac.uk/pdbe/static/entry/1ci6_updated.cif it only has annotation for chain B and not A. If the secondary structure annotation for any chain is present, I do not compute it at all.

Ideally, I should be able to give option to the user if to approximate (because LiteMol currently only implements a very basic algorithm for that) the structure or use the input annotation. This feature is coming eventually...

David

**Comment by davidjakubec** [comment]
Hi,

thank you, I realize that some structures are problematic.

David
