### ISSUE TITLE
Density display issue

### ISSUE THREAD

**Issue by mandarsd** [dsehnal/LiteMol#33]
Density appears when we click/select an atom. If we click on the same atom again then density disappears and keeps on toggling on selection.

**Comment by dsehnal** [comment]
This is intended behavior caused by the 'UnselectElementOnRepeatedClick' behaviour.

If you remove it from the plugin spec,  this should no longer occur. However, there might be some other functionality in your case that relies on this (but maybe not).

Alternatively, it might be possible to add "Show Always" toggle for the density streaming behaviour which would keep the density shown for the latest active selection.

For a quick fix, you might try to remove this line https://github.com/dsehnal/LiteMol/blob/master/src/Viewer/Extensions/DensityStreaming/Behaviour.ts#L294 and the density should stay always on.

**Comment by mandarsd** [comment]
Aha! Got it. Quick fix did the trick.
