### ISSUE TITLE
How to use position relative?

### ISSUE THREAD

**Issue by pslacerda** [dsehnal/LiteMol#56]
Hi,

I'm trying to place the LiteMol on a HTML without React. Some `div`'s have position absolute with margins set to 0. This behavior occludes any other widgets on my page. 

The usage is too hard for me, I'm struggling at PluginSpec. What can I do to display only the viewer's area? Last question is how to draw some mesh? Or better something like [Pymol's map and volume commands](https://pymolwiki.org/index.php/Volume), semi-transparent smoothed volume colored by atom (instead of electron) density?

**Comment by dsehnal** [comment]
Hi,

if it's still relevant:

> I'm trying to place the LiteMol on a HTML without React. Some div's have position absolute with margins set to 0. This behavior occludes any other widgets on my page.

Maybe just set the expanded state of the plugin to false. Then standard CSS works. The expanded state by design occludes everything. 

> The usage is too hard for me, I'm struggling at PluginSpec. What can I do to display only the viewer's area? 

Most of the examples show how to do this, most notably the Commands one.

> Last question is how to draw some mesh? Or better something like Pymol's map and volume commands, semi-transparent smoothed volume colored by atom (instead of electron) density?

Unfortunately, to color custom mesh by atom, you would have to write the function yourself. But otherwise, the "element symbol" coloring for example is avaiable for all the representation, which include a surface.

**Comment by pslacerda** [comment]
I moved on. Thank you.
