### ISSUE TITLE
Can LiteMol load a molecule from a file instead that from a url?

### ISSUE THREAD

**Issue by mb925** [dsehnal/LiteMol#61]
I am using the following function to load a molecule:
await this.ltplugin.loadMolecule({
          id: ids,
          url: this.url,
          format: 'cif',
          modelRef: 'model',
          doNotCreateVisual: true
        });

Can I upload a PDB chain from a local file instead that from a url?
Thank you.

**Comment by dsehnal** [comment]
- You can open a file, yes. But that generally requires user interaction.
- If the file is in the same directory as the page with litemol, just using the filename as URL should work.
- You can try using ``file://path`` in the URL but your browser will probably complain and it will only work on your PC.
- Otherwise you always have to host the file somewhere, in which case you will have URL.

Alternatively, if you mean that you already have the string with the file, you can also do that. Just use ``{ ..., data: ..., ...}`` instead of the ``url`` param. And change the format to ``pdb`` if it's a PDB file.

**Comment by mb925** [comment]
Thank you for your help. We will host the files as suggested in your answer. 

In order to speed the loading of molecules, does LiteMol support compressed files and/or MMTF format?

**Comment by dsehnal** [comment]
Well, if this is a new integration, I recommend you use Mol* (https://molstar.org/) which is successor to both LiteMol and NGL.

LiteMol and Mol* support BinaryCIF (publication is coming out soon) which superseeds MMTF and is available at both RCSB and PDBe.
